# Generated by Django 3.0.5 on 2020-05-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option_eight_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_five_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_four_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_nine_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_one_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_seven_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_six_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_ten_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_three_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_two_count',
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_eight',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_five',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_four',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_nine',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_one',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_seven',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_six',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_ten',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_two',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=9),
        ),
    ]
