# Generated by Django 3.0.5 on 2020-05-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200525_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_eight',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_five',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_four',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_nine',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_one',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_seven',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_six',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_ten',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_two',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
